---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
        args: [--allow-multiple-documents]
        # Helm templates have {{ ... }} which fail YAML validation.
        exclude: charts/.+
    -   id: debug-statements
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
        args: [--fix=no]
    -   id: pretty-format-json
        args: [--autofix]
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
