name: Build and scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

env:
  ARCH: amd64
  IMAGE: "thirdparty/knote-js"
  NODEJS_IMAGE: node:18-alpine

jobs:
  build-and-scan:
    name: Build and scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: zilliqa-hw/img-build-tools-library
          path: img-build-tools-library
          ssh-key: ${{ secrets.GH_IMG_LIBRARY_DEPLOY_KEY }}

      - name: AWS authentication - dev
        if: "!startsWith(github.ref, 'refs/heads/main')"
        uses: ./img-build-tools-library/.github/actions/aws_auth
        with:
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID_ENGINEERING_DEV }}
          aws_profile: z-engineering-dev-cicd
          home_aws_config: ${{ secrets.HOME_AWS_CONFIG }}
          home_aws_credentials: ${{ secrets.HOME_AWS_CREDENTIALS }}

      - name: AWS authentication - shared services
        if: "startsWith(github.ref, 'refs/heads/main')"
        uses: ./img-build-tools-library/.github/actions/aws_auth
        with:
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID_SHARED_SERVICES }}
          aws_profile: z-shared-services-cicd
          home_aws_config: ${{ secrets.HOME_AWS_CONFIG }}
          home_aws_credentials: ${{ secrets.HOME_AWS_CREDENTIALS }}

      - name: Environment setup - dev
        if: "!startsWith(github.ref, 'refs/heads/main')"
        uses: ./img-build-tools-library/.github/actions/setup

      - name: Environment setup - shared services
        if: startsWith(github.ref, 'refs/heads/main')
        uses: ./img-build-tools-library/.github/actions/setup
        with:
          ecr_server_host: ${{ secrets.AWS_ACCOUNT_ID_SHARED_SERVICES }}.dkr.ecr.eu-central-1.amazonaws.com

      - name: Set up Docker Buildx
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: npm ci
        run: |
          docker run -v $(pwd):$(pwd) -w $(pwd) ${{ env.NODEJS_IMAGE }} npm ci

      - name: Build
        # For tagged releases, don't build but pull the image. See the next step.
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: docker/build-push-action@v3
        with:
          build-args: |
            ARCH=${{ env.ARCH }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: .
          file: ./Dockerfile
          # See https://github.com/opencontainers/image-spec/blob/master/annotations.md
          labels: |
            org.opencontainers.image.created=${{ env.CREATED }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.documentation=${{ github.event.repository.repo.url }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
            org.opencontainers.image.ref.name=${{ steps.prep.outputs.git_branch }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.title=${{ env.IMAGE }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          platforms: linux/amd64
          load: true
          push: false
          tags: "${{ env.IMAGE_NAME_FULL}}"

      - name: Pull the image before release
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker pull ${{ env.IMAGE_NAME_FULL }}

      - name: Assets/AV scan
        uses: ./img-build-tools-library/.github/actions/scanning

      - name: Push the image to ECR
        run: docker push ${{ env.IMAGE_NAME_FULL }}

      - name: Publish the image as a release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ./img-build-tools-library/.github/actions/release_image
