name: Linting
on:
  push:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python setup
        uses: actions/setup-python@v3
      - name: pre-commit setup
        uses: pre-commit/action@v3.0.0
